# Generated by Django 2.0.2 on 2018-03-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='bond_term',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=19),
        ),
        migrations.AddField(
            model_name='input',
            name='deposit_paid',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=19),
        ),
        migrations.AddField(
            model_name='input',
            name='fixed_interest_rate',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=19),
        ),
        migrations.AlterField(
            model_name='input',
            name='purchase_price',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=19),
        ),
    ]
