# Generated by Django 2.0.2 on 2018-03-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_auto_20180302_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='monthly_payments',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
