# Generated by Django 2.0.2 on 2018-03-02 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_auto_20180302_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='monthly_payments',
        ),
    ]
