# Generated by Django 3.2.12 on 2022-07-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_remove_input_monthly_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='bond_term',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='input',
            name='deposit_paid',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=19),
        ),
        migrations.AlterField(
            model_name='input',
            name='fixed_interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='input',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=19),
        ),
    ]
