# Generated by Django 3.2.12 on 2022-07-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_auto_20220703_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='fixed_interest_rate',
            field=models.DecimalField(decimal_places=50, default=0.1, max_digits=50),
        ),
    ]
