# Generated by Django 3.2.12 on 2022-07-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_alter_input_fixed_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='fixed_interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=19),
        ),
    ]
